const pathParts=location.pathname.split('/').filter(Boolean);const inboxId=decodeURIComponent(pathParts[1]||'');const params=new URLSearchParams(location.search);const address=params.get('address')||'';const token=params.get('token')||'';
const $=s=>document.querySelector(s);const el={address:$('#publicEmailAddress'),status:$('#publicStatus'),copy:$('#copyPublicAddressButton'),refresh:$('#refreshPublicButton'),search:$('#publicSearchInput'),list:$('#publicMessageList'),viewer:$('#publicMessageViewer'),count:$('#messageCount'),toast:$('#toast')};
const state={messages:[],selectedMessageId:null,timer:null};
function escapeHtml(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function formatDate(v){if(!v)return'未知时间';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);}
function toast(m){el.toast.textContent=m;el.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.toast.classList.remove('show'),2300);}
async function api(path){const r=await fetch(path,{headers:{Accept:'application/json'}});let p;try{p=await r.json();}catch{p={error:'服务器返回了无法解析的内容。'};}if(!r.ok)throw new Error(p.error||`请求失败（${r.status}）`);return p;}
function authQuery(extra=''){const q=new URLSearchParams({address,token});if(extra)q.set('search',extra);return q.toString();}
function renderList(){el.count.textContent=`${state.messages.length} 封`;if(!state.messages.length){el.list.className='message-list empty-state';el.list.innerHTML='<div><div class="empty-icon">✉</div><p>这个邮箱暂时还没有邮件</p></div>';return;}el.list.className='message-list';el.list.innerHTML=state.messages.map(m=>`<button class="message-item ${state.selectedMessageId===m.message_id?'active':''}" type="button" data-message-id="${escapeHtml(m.message_id)}"><span class="message-row"><span class="message-from">${escapeHtml(m.from||'未知发件人')}</span><span class="message-time">${formatDate(m.timestamp)}</span></span><span class="message-subject">${escapeHtml(m.subject||'（无主题）')}</span><span class="message-preview">${escapeHtml(m.preview||'暂无预览')}</span></button>`).join('');}
function renderDetail(m){const attachments=Array.isArray(m.attachments)&&m.attachments.length?`<div class="attachments"><strong>附件</strong><div>${m.attachments.map(a=>`<span class="attachment-chip">${escapeHtml(a.filename||'未命名附件')} (${Math.ceil((a.size||0)/1024)} KB)</span>`).join('')}</div></div>`:'';el.viewer.className='message-detail';el.viewer.innerHTML=`<header class="message-detail-header"><h2>${escapeHtml(m.subject||'（无主题）')}</h2><div class="message-meta"><div><strong>发件人：</strong>${escapeHtml(m.from||'未知')}</div><div><strong>收件人：</strong>${escapeHtml((m.to||[]).join(', ')||address||'未知')}</div><div><strong>时间：</strong>${escapeHtml(formatDate(m.timestamp))}</div></div></header><div class="message-body"><pre>${escapeHtml(m.text||'这封邮件没有可显示的正文。')}</pre>${attachments}</div>`;}
async function loadMessages(){if(!inboxId||!token){el.status.textContent='链接无效';el.status.className='status-pill offline';el.list.innerHTML='<div class="error-box">专属链接不完整或已失效。</div>';return;}el.refresh.disabled=true;el.list.className='message-list';el.list.innerHTML='<div class="loading-row">正在加载邮件…</div>';try{const data=await api(`/api/public/inboxes/${encodeURIComponent(inboxId)}/messages?${authQuery(el.search.value.trim())}`);state.messages=(data.messages||[]).sort((a,b)=>new Date(b.timestamp||0)-new Date(a.timestamp||0));el.status.textContent='邮箱已连接';el.status.className='status-pill online';renderList();}catch(e){el.status.textContent='无法访问';el.status.className='status-pill offline';el.list.innerHTML=`<div class="error-box">${escapeHtml(e.message)}</div>`;toast(e.message);}finally{el.refresh.disabled=false;}}
async function openMessage(id){state.selectedMessageId=id;renderList();el.viewer.className='viewer-empty';el.viewer.innerHTML='<div><p>正在加载邮件正文…</p></div>';try{const m=await api(`/api/public/inboxes/${encodeURIComponent(inboxId)}/messages/${encodeURIComponent(id)}?${authQuery()}`);renderDetail(m);}catch(e){el.viewer.innerHTML=`<div class="error-box">${escapeHtml(e.message)}</div>`;toast(e.message);}}
el.address.textContent=address||'专属邮箱';document.title=`${address||'邮箱'} - 查看邮件`;
el.copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(address);toast('邮箱地址已复制');}catch{toast('复制失败，请手动复制');}});
el.refresh.addEventListener('click',loadMessages);el.list.addEventListener('click',e=>{const b=e.target.closest('[data-message-id]');if(b)openMessage(b.dataset.messageId);});el.search.addEventListener('input',()=>{clearTimeout(state.timer);state.timer=setTimeout(loadMessages,350);});
await loadMessages();setInterval(()=>{if(document.visibilityState==='visible')loadMessages();},15000);
